name: checkin

on:
  schedule:
    - cron: "0 0,8 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 运行打卡脚本
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: |
          python sduhealth.py
